HANG_MAN_PARTS = {
    5: "_______\n|      |\n|\n|\n|\n|\n|\n|\n|",
    4: "_______\n|      |\n|     -----\n|     |   |\n|     -----\n|\n|\n|\n|",
    3: "_______\n|      |\n|     -----\n|     |   |\n|     -----\n|      |\n|      |\n|\n|",
    2: "_______\n|      |\n|     -----\n|     |   |\n|     -----\n|      /|/\n|      |\n|\n|",
    1: "_______\n|      |\n|     -----\n|     |   |\n|     -----\n|      /|/\n|      |\n|      //\n|"
}

WORDS = [
"vortex",
"voyeurism",
"walkway",
"waltz",
"wave",
"wavy",
"waxy",
"wellspring",
"wheezy",
"whiskey",
"whizzing",
"whomever",
"wimpy",
"witchcraft",
"wizard",
"woozy",
"wristwatch",
"wyvern",
"xylophone",
"yachtsman",
"yippee",
"yoked",
"youthful",
"yummy",
"zephyr",
"zigzag",
"zigzagging",
"zilch",
"zipper",
"zodiac",
"zombie"]